### ISSUE TITLE
npm start command is failing

### ISSUE THREAD

**Issue by nzeugaa** [oliviertassinari/SplitMe#24]
Hi,
I wanted to run this project (to see pouchdb in action). But running `npm start` failed with : 

> Error: Cannot find module '/home/xxx/SplitMe/server/local/server.js'

Looks like file `server/local/server.js` is missing. Is this file generated ? Furthermore directory `/server/local/` is listed in `.gitignore`. Why ?

Thanks for your help.

**Comment by oliviertassinari** [comment]
The `npm start` is intended for the production environment, that would work locally without the assets bundled. try `npm run server:development` and `npm run browser:development`.

**Comment by oliviertassinari** [comment]
Thanks for having a look at the project 😄 .

**Comment by nzeugaa** [comment]
Should I run the two commands for development mode ? i.e `npm run server:development` then `npm run browser:development` or only one command.
What I understand is that `npm run server:development` will launch the server part and `npm run browser:development` will launch the client (browser in this case) part and the two commands are mandatory in order to launch development mode. Correct me if I'm wrong. Thanks a lot.

**Comment by oliviertassinari** [comment]
yeah, you need to have both running at the same time to make in work in the dev environment.

**Comment by oliviertassinari** [comment]
@nzeugaa Did you figured out how to make it work?

**Comment by nzeugaa** [comment]
@oliviertassinari I was able to launch the server. But when I click on `TRY SPLITME` on the main page nothing is happening.  This error is displayed on the browser debug console : 
`Refused to execute script from 'http://localhost:8080/browser.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`
I've also run `npm run browser:development` on a distinct terminal.

**Comment by oliviertassinari** [comment]
Did you navigated to `localhost:8000`?

**Comment by nzeugaa** [comment]
I was on `localhost:8080`. Navigating to `localhost:8000` shows an error : 
> Error occured while trying to proxy to: localhost:8000/

And on the console :
 
> [HPM] Error occurred while trying to proxy request /favicon.ico from localhost:8000 to http://local.splitme.net:8080 (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)

So, localhost:8000 is the server rendering and localhost:8080 is the client rendering ? right ? what is http://local.splitme.net:8080 for ?

**Comment by oliviertassinari** [comment]
The server is listening on the [8080 port](https://github.com/oliviertassinari/SplitMe/blob/master/src/app.server.js#L10)
The client is listening on the [8000 port](https://github.com/oliviertassinari/SplitMe/blob/master/webpack.js#L11) and proxy request to the sever, it's the entrypoint of all the requests.

**Comment by nzeugaa** [comment]
So, looks like the there is a problem setting up the proxy, it's not resolvable that's why I am having : 

> [HPM] Error occurred while trying to proxy request /favicon.ico from localhost:8000 to http://local.splitme.net:8080 (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by oliviertassinari** [comment]
Oh, well you are right, I have been adding `http://local.splitme.net/` to my host, that's forwarded to 0.0.0.0. That won't work without.

**Comment by nzeugaa** [comment]
Its works with 0.0.0.0 !!
Where in the code is done browser/cordova detection in order to choose the right index.html to be returned (production mode) ? I'm trying to understand the code. Thanks again.

**Comment by nzeugaa** [comment]
In fact no need a detection since it's different targets. Thanks for your help @oliviertassinari .
