### ISSUE TITLE
Supporting pop state in tab-views

### ISSUE THREAD

**Issue by piyushchauhan2011** [oliviertassinari/SplitMe#26]
I noticed when we click the browser back button, user doesn't get redirected back to previously pushed tab but get's redirected to `/account` I believe. Currently, I saw that `replace` is used to achieve this. Is it possible to somewhat support the window `popstate` with drag feature of `SwipeableView` ?

**Comment by oliviertassinari** [comment]
This `replace` behavior is intentional. It feets best what we can find with native apps. Yes, anything is possible.

**Comment by piyushchauhan2011** [comment]
Hmm, right. Is it possible to integrate a `push` behaviour so that the swipe animation could be integrated with the react-routing ?

**Comment by piyushchauhan2011** [comment]
I will probably make a simple app to test it out and post the link here ?

**Comment by oliviertassinari** [comment]
Sorry, I don't understand the motivation here. Is this issue regarding improving SplitMe?

**Comment by piyushchauhan2011** [comment]
Hey @oliviertassinari, sorry for the above. I'll probably close this issue. I thought integrating `push` seems a good behaviour as to `replace`. Thanks for getting back to me 😃
